# Alex Shoop makefile for CS 3516 Project 3 - Distance Vector routing protocol

all: project3

project3: project3.c node0.c node1.c node2.c node3.c
	gcc -Wall project3.c node0.c node1.c node2.c node3.c -o project3   

clean:
	rm -f *.o project3
